version: '3.3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    depends_on:
      - db
    container_name: foodgram-backend
    image: mishatunikov/foodgram_backend:latest
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    container_name: foodgram-front
    image: mishatunikov/foodgram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  nginx:
    depends_on:
      - frontend
      - backend
    container_name: foodgram-proxy
    image: mishatunikov/foodgram_gateway:latest
    ports:
      - "7000:80"
    volumes:
      - static:/static
      - media:/media
