# Generated by Django 3.2.16 on 2025-04-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_rename_measure_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
