# Generated by Django 3.2.16 on 2025-04-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_rename_description_recipe_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='count_ingredient',
            new_name='amount',
        ),
    ]
