# Generated by Django 3.2.16 on 2025-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_auto_20250424_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link_id',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
