# Generated by Django 3.2.16 on 2025-04-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_recipe_short_link_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('id',)},
        ),
    ]
