# Generated by Django 3.2.16 on 2025-05-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0013_auto_20250509_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
