MAX_SLUG_LENGTH = 50
MAX_NAME_FIELD = 256
MEASURE_UNIT_LENGTH = 20
MAX_SHORT_LINK_ID_LENGTH = 6

HTTPS_STARTSWITH = 'https://'
HTTP_STARTSWITH = 'http://'
SHORT_URL_ENDPOINT = 's'

ADMIN_PANEL_MAX_WORDS = 10

MIN_AMOUNT_INGREDIENT = 1
MAX_AMOUNT_INGREDIENT = 10_000

MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 5_000
