# Generated by Django 4.2.20 on 2025-04-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(
                default=None, null=True, upload_to='avatars'
            ),
        ),
    ]
